from nkululeko.constants import VERSION
from setuptools import setup, find_packages

setup(
    name="nkululeko",
    version=VERSION,
    description="Machine learning audio prediction experiments based on templates",
    author="Felix Burkhardt",
    author_email="fxburk@gmail.com",
    url="https://github.com/felixbur/nkululeko",
    packages=find_packages(),
    python_requires=">=3.9",
    install_requires=[
        "audeer",
        "audformat",
        "audinterface",
        "audiofile",
        "audiomentations",
        "audmetric",
        "audonnx",
        "confidence_intervals",
        "datasets",
        "imageio",
        "matplotlib",
        "numpy",
        "opensmile",
        "pandas",
        "praat-parselmouth",
        "scikit_learn",
        "scipy",
        "seaborn",
        "sounddevice",
        "torch",
        "torchvision",
        "torchaudio",
        "transformers",
        "umap-learn",
        "xgboost",
        "pylatex",
    ],
    entry_points={
        "console_scripts": [
            "nkululeko.explore=nkululeko.explore:main",
            "nkululeko.nkululeko=nkululeko.nkululeko:main",
            "nkululeko.augment=nkululeko.augment:main",
            "nkululeko.demo=nkululeko.demo:main",
            "nkululeko.export=nkululeko.export:main",
            "nkululeko.predict=nkululeko.predict:main",
            "nkululeko.resample=nkululeko.resample:main",
            "nkululeko.segment=nkululeko.segment:main",
            "nkululeko.test=nkululeko.test:main",
            "nkululeko.ensemble=nkululeko.ensemble:main",
        ],
    },
)
