sonar.projectKey=bagustris_nkululeko
sonar.organization=bagustris

sonar.sources=nkululeko
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=nkululeko/openXBOW/**
