python -m nkululeko.explore --config tests/exp_emodb_explore_data.ini
python -m nkululeko.explore --config tests/exp_emodb_explore_tsne.ini
python -m nkululeko.explore --config tests/exp_emodb_explore_features.ini
python -m nkululeko.nkululeko --config tests/exp_emodb_os_praat_xgb.ini
python -m nkululeko.nkululeko --config tests/exp_emodb_os_mlp.ini
python -m nkululeko.nkululeko --config tests/exp_agedb_os_xgr.ini 
python -m nkululeko.nkululeko --config tests/exp_agedb_os_mlp.ini 
python -m nkululeko.nkululeko --config tests/exp_agedb_class_os_xgb.ini 
python -m nkululeko.augment --config tests/exp_emodb_augment_os_xgb.ini
python -m nkululeko.nkululeko --config tests/exp_emodb-aug_os_xgb.ini