; Example INI file for segmentation using SEGMENT module (silero)
; Checking also silence segmentation
[EXP]
root = ./examples/results/
name = exp_emodb_segment
runs = 1
epochs = 1
save = True
sample_selection = all
[DATA]
databases = ['emodb']
emodb = ./data/emodb/emodb
# only audio files, no laryngograms
emodb.files_tables = ['emotion.categories.test.gold_standard', 'emotion.categories.train.gold_standard', 'emotion.categories.ambiguous']
emodb.split_strategy = random
target = emotion
labels = ['anger', 'neutral']
[SEGMENT]
method = silero
segment_target = _segmented
; Apply to all samples
[MODEL]
type = svm
[FEATS]
type = ['os']
scale = standard
