import os

import yaml
from mdutils import MdUtils

# Determine the root directory - support running from both data/ and repository root
if os.path.basename(os.getcwd()) == "data":
    root = "."
else:
    root = "./data"

mdFile = MdUtils(
    file_name=os.path.join(root, "README.md"), title="Nkululeko Data Directory"
)
mdFile.create_md_file()
mdFile.new_header(level=1, title=" ")
mdFile.new_paragraph(
    "This is the default top directory for Nkululeko data import. "
    "Each database should be in its own subfolder "
    "(you can also use `ln -sf` to soft link the original database "
    "path to these subfolders) "
    "and contain a README on how to import the data to Nkululeko CSV or audformat."
    "This README file is automatically generated by "
    "`data/make_readme.py` script (needs `mdutils` package). "
    "To update this file, run the script again after adding new datasets "
    "and adding the necessary information to each database folder's `descr.yml` file. "
)
mdFile.new_header(level=2, title="Accessibility")
mdFile.new_paragraph(
    "The column `access` in the table below indicates "
    "the database's accessibility. The following values are used:"
)
mdFile.new_list(
    [
        "`public`: the database is publicly available on the internet "
        "and can be downloaded directly without any restrictions.",
        "`restricted`: the database is publicly available on the internet "
        "but requires registration or other restrictions to download.",
        "`private`: the database is not publicly available on the internet "
        "and requires the private information of the owner of the dataset.",
    ]
)
mdFile.new_paragraph(
    "To support open science and reproducible research, "
    "we encourage you to submit PR and recipes for the public dataset for "
    "now on."
)

# Scan all database folders and read their descr.yml files
datasets = []
db_num = 0

# Get all subdirectories in the data folder
for entry in os.listdir(root):
    folder_path = os.path.join(root, entry)

    # Skip if not a directory
    if not os.path.isdir(folder_path):
        continue

    # Look for descr.yml in the folder
    descr_file = os.path.join(folder_path, "descr.yml")
    if os.path.exists(descr_file):
        try:
            with open(descr_file, "r") as f:
                descr = yaml.safe_load(f)

            # Handle both old (list-based) and new (dict-based) formats
            if isinstance(descr, dict) and "name" in descr:
                # New format: simple dictionary
                datasets.append(
                    {
                        "name": descr.get("name", entry),
                        "folder": entry,
                        "target": descr.get("target", "unknown"),
                        "description": descr.get("description", ""),
                        "access": descr.get("access", "unknown"),
                        "license": descr.get("license", "unknown"),
                    }
                )
                db_num += 1
            else:
                print(f"Warning: {descr_file} has unexpected format, skipping.")
        except Exception as e:
            print(f"Error reading {descr_file}: {e}")

# Sort datasets by name for consistent ordering
datasets.sort(key=lambda x: x["name"].lower())

# Build the table
table_list = ["Name", "Target", "Description", "Access", "License"]
for ds in datasets:
    # Create markdown link for the database name
    name_link = f"[{ds['name']}]({ds['folder']}/)"
    table_list.extend(
        [name_link, ds["target"], ds["description"], ds["access"], ds["license"]]
    )

mdFile.new_table(columns=5, rows=db_num + 1, text=table_list, text_align="left")

# add information about number of datasets
mdFile.new_paragraph(f"This recipe contains information about {db_num} datasets.")

mdFile.new_header(level=2, title="Performance")
mdFile.new_line(
    mdFile.new_inline_image(
        text="Nkululeko performance", path="../meta/images/nkululeko_ser_20240719.png"
    )
)
mdFile.new_line()
mdFile.create_md_file()

print(f"README.md file created with {db_num} datasets in {root} directory.")
