name: Test Installation Python 3.11

on: [push, pull_request]

jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Test installation
      run: |
        pip install upgrade pip 
        python tests/test_install.py
